# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 20 Mar 2020 20:30:14 +0000
*               @ALL          0
*               @user         8
