<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: victor
 * Date: Sat, 21 Mar 2020 13:08:27 +0000
 */

$conf['title'] = 'VICSOFT Wiki';
$conf['lang'] = 'es';
$conf['template'] = 'mindthedark';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;

// end auto-generated content
